title: [Lockdown recipes]
description: [Pretty bad recipes written during (or for use during) lockdown]
theme: jekyll-theme-merlot
category-list: [
    inspired-by-name,
    drinks,
    air-fryer,
    gin,
    roast,
    beef,
    brisket,
    bourbon,
    gurvansh,
    meat,
]
